---
arturl_encode: "68747470733a2f2f626c6f:672e6373646e2e6e65742f7869616f6368656e58494855412f:61727469636c652f64657461696c732f313333323334313930"
layout: post
title: "C中实现单元测试的示例流程_MSTest测试项目"
date: 2023-09-24 20:16:53 +0800
description: "​在《单元测试艺术》一书中对于单元测试的定义是：【一个单元测试是一段代码，这段代码调用一个工作单元（"
keywords: "c# 单元测试"
categories: ['C']
tags: ['测试项目', '单元测试示例', '单元测试流程', '单元测试', 'Mstest', 'C']
artid: "133234190"
image:
    path: https://api.vvhan.com/api/bing?rand=sj&artid=133234190
    alt: "C中实现单元测试的示例流程_MSTest测试项目"
render_with_liquid: false
featuredImage: https://bing.ee123.net/img/rand?artid=133234190
featuredImagePreview: https://bing.ee123.net/img/rand?artid=133234190
---

# C#中实现单元测试的示例流程\_MSTest测试项目

## 一、单元测试简介

### 1.1、单元测试简介

在《
[单元测试艺术](https://book.douban.com/subject/25934516/?channel=subject_list&platform=web "单元测试艺术")
》一书中对于单元测试的定义是：【
**一个单元测试是一段代码，这段代码调用一个工作单元**
（指：调用软件中的一个方法，这个方法执行过程中所发生的所有行为以及最后产生的结果的总和）
**，并检验该工作单元的一个具体的结果。如果关于这个结果的最终假设是错误的，单元测试就失败了；一个单元测试的范围可以小到一个方法，大到多个类**
】

### 1.2、单元测试的意义

要注意：引入单元测试或有单元测试并不能证明代码质量好（应根据项目情况进行调整适配，比如优先考虑核心模块），单元测试并不是越多越好（不要忽视引入代码测试以及无效的测试所带来的维护成本【如：增加开发的时间、增加人员成本】，毕竟资源是有限的）。

若不考虑时间成本，还是希望各位可以为代码编写高效可靠的单元测试，毕竟这对提升代码质量有帮助；而单元测试具有如下意义：

1、通过单元测试用例确保的功能，不会在后续的迭代过程中产生Bug；

2、在重构模块时，因为有单元测试覆盖，也可以大胆去做；

3、可以通过单元测试模块了解模块具体功能和预期；

4、提高代码质量，降低耦合；

![](https://i-blog.csdnimg.cn/blog_migrate/07fc4d0126c7fcff49948c05c7e96ee2.gif)

## 二、单元测试示例流程

### 2.1、打开VisualStudio创建项目

**1、使用VisualStudio创建一个跨平台的控制台项目（取名为：Test\_UnitTest），如下图所示：**

![](https://i-blog.csdnimg.cn/blog_migrate/38e51d4461149ce6291fae6a079df7cf.png)

![](https://i-blog.csdnimg.cn/blog_migrate/bac7748086f5ee57a114107482ba77cf.png)

![](https://i-blog.csdnimg.cn/blog_migrate/2d7a0e5550b810aa60d6483f3d348889.png)

**2、新建一个名为： BankAccount 的银行账户类**

```cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace test_UnitTest
{
    public class BankAccount
    {
        private readonly string m_customerName;
        private double m_balance;

        public BankAccount(string customerName,double balance)
        {
            m_customerName = customerName;
            m_balance = balance;

            Console.WriteLine($"\n初始的余额是【{Balance}】");
        }

        public string CustomerName
        {
            get { return m_customerName; }
        }

        public double Balance
        {
            get { return m_balance; } 
        }

        /// <summary>
        /// 借钱出去
        /// </summary>
        /// <param name="amout">金额</param>
        /// <exception cref="ArgumentOutOfRangeException"></exception>
        public void Debit(double amout)
        {
            if (amout>m_balance)
            {
                throw new ArgumentOutOfRangeException("amount");
            }
            if (amout<0)
            {
                throw new ArgumentOutOfRangeException("amount");
            }
            m_balance += amout;
            Console.WriteLine($"借钱【{amout}】出去后的余额是【{Balance}】");
        }

        public const string DebitAmountExceedsBalanceMessage = "当前借出的金额超过当前的余额";
        public const string DebitAmountLessThanZeroMessage = "当前借出的金额小于0";

        /// <summary>
        /// 借钱出去
        /// </summary>
        /// <param name="amout">金额</param>
        /// <exception cref="ArgumentOutOfRangeException"></exception>
        public void Debit2(double amout)
        {
            if (amout > m_balance)
            {
                throw new ArgumentOutOfRangeException("amount",amout, DebitAmountExceedsBalanceMessage);
            }
            if (amout < 0)
            {
                throw new ArgumentOutOfRangeException("amount",amout, DebitAmountLessThanZeroMessage);
            }
            m_balance += amout;
            Console.WriteLine($"借钱【{amout}】出去后的余额是【{Balance}】");
        }

        /// <summary>
        /// 贷款进来
        /// </summary>
        /// <param name="amout">金额</param>
        /// <exception cref="ArgumentOutOfRangeException"></exception>
        public void Credit(double amout)
        {
            if (amout<0) 
            {
                throw new ArgumentOutOfRangeException("amout");
            }
            m_balance += amout;
            Console.WriteLine($"贷款【{amout}】进来后的余额是【{Balance}】");
        }


    }//Class_end
}

```

**3、运行该银行账户类**

```cs
namespace test_UnitTest
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello, World!");
            BankAccount ba = new BankAccount("张三", 11.99);

            ba.Credit(5.77);
            ba.Debit(11.22);
            Console.WriteLine($"当前账户的余额是 ${ba.Balance}");

            Console.ReadLine();
        }


    }
}
```

![](https://i-blog.csdnimg.cn/blog_migrate/7339cf349305bb865bbeb2c7c908edda.png)

**到目前为止程序是没有报错的；但是仔细查看我们就会发现一个问题，借钱出去后，我们的银行账户应该是余额减少的；但是我们的程序却显示余额增加了，这明显是错误的；关于这样的类似错误我们可以通过单元测试来避免，修复这个Bug。**

### 2.2、创建单元测试项目

#### **2.2.1、新增单元测试项目，并且添加项目引用**

![](https://i-blog.csdnimg.cn/blog_migrate/661bb46ab69d3d4bf6c58f3b1cffd643.png)

![](https://i-blog.csdnimg.cn/blog_migrate/36e3105cc5ec42bb31f8edfeb069fad5.png)

![](https://i-blog.csdnimg.cn/blog_migrate/012b85f853dd4d91f741490a5c912ffe.png)

![](https://i-blog.csdnimg.cn/blog_migrate/feef4c516461e119e1d26d72472d6751.png)

![](https://i-blog.csdnimg.cn/blog_migrate/e0c40dfe681fc4264875b7d30e3fccab.png)

#### **2.2.2、创建单元测试类BankAccountTest.cs**

将默认的UnitTest1.cs类修改名称为【
**BankAccountTest.cs**
】，默认的测试类示例如下

```cs
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace BankTests
{
    [TestClass]
    public class BankAccountTests
    {
        [TestMethod]
        public void TestMethod1()
        {
        }
    }
}
```

**其中【TestClass】标识该类是一个单元测试类；【TestMethod】标识该方法是一个单元测试方法。**

#### **2.2.3、编写一个单元测试的示例方法**

单元测试方法的必备要求

|  |  |
| --- | --- |
| 序号 |  |
| 1 | **必须使用 `[TestMethod]` 特性进行修饰** |
| 2 | 方法 **必须返回 `void`** |
| 3 | 单元测试方法必须 **不能含有参数** |
| `Assert.AreEqual` 、 [Assert.IsTrue](https://learn.microsoft.com/zh-cn/dotnet/api/microsoft.visualstudio.testtools.unittesting.assert.istrue "Assert.IsTrue") 等方法经常用于单元测试 [Assert Class (Microsoft.VisualStudio.TestTools.UnitTesting) | Microsoft Learn](https://learn.microsoft.com/zh-cn/dotnet/api/microsoft.visualstudio.testtools.unittesting.assert?view=visualstudiosdk-2022 "Assert Class (Microsoft.VisualStudio.TestTools.UnitTesting) | Microsoft Learn") | |

**①分析：编写单元测试方法以验证
`BankAccount`
类的
`Debit`
方法的行为，则至少需要检查三种行为：**

* 如果借方金额大于余额，该方法将引发
  [ArgumentOutOfRangeException](https://learn.microsoft.com/zh-cn/dotnet/api/system.argumentoutofrangeexception "ArgumentOutOfRangeException")
  。
* 如果借方金额小于零，该方法会引发
  [ArgumentOutOfRangeException](https://learn.microsoft.com/zh-cn/dotnet/api/system.argumentoutofrangeexception "ArgumentOutOfRangeException")
  。
* 如果借方金额有效，该方法会从帐户余额中减去该借方金额。

**②第一个单元测试方法：验证是否从帐户中提取了正确的有效金额（即小于帐户余额且大于零）**
；将以下方法添加到该
`BankAccountTests`
类：

```cs
        [TestMethod]
        //验证借出指定的金额后是否与预期的金额相等
        public void Debit_WithValidAmount_UpdatesBalance()
        {

            double beginningBalance = 11.99;    //初始金额
            double debitAmount = 4.55;          //借出去的金额数量
            double expected = 7.44;             //进出金额后期望剩余的金额数量
            BankAccount account = new BankAccount("张三", beginningBalance);

            account.Debit(debitAmount);

            double actual = account.Balance;
            //判断是否相等[若不相等则抛出异常]
            Assert.AreEqual(expected, actual, 0.001, "该账户的金额并没有正确的借出去！！！");
        }
```

**③生成并运行单元测试和解决错误**

首先生成解决方案

![](https://i-blog.csdnimg.cn/blog_migrate/8b4bab61f72b290c9b99b961d9aa5f09.png)

然后选择顶部的【测试】-->【运行所有测试】结果如下：

![](https://i-blog.csdnimg.cn/blog_migrate/3adf3d2d85d299fe0e05b2e5236ba126.png)

![](https://i-blog.csdnimg.cn/blog_migrate/081115cc2b237e96bfb67e59f756c17c.png)

最后根据单元测试的错误提示排查是由于调用账户的借出金额后的余额与期望的余额不一致导致报错，我们需要排查【account.Debit()】方法，需要将【account.Debit()】方法的 m\_balance += amout;修改为 m\_balance -= amout;后保存重新【运行所有测试】即可通过单元测试），如下图所示：

![](https://i-blog.csdnimg.cn/blog_migrate/bf8522b67fd56d35a3f7fe867f8f8f2b.png)

![](https://i-blog.csdnimg.cn/blog_migrate/7607621107664651dc2d87fe5d89511a.png)

**BankAccountTest.cs银行账户的完整单元测试类内容如下：**

**具体的每步细节可以查看如下的链接**

[C# 单元测试教程 - Visual Studio (Windows) | Microsoft Learn

了解如何使用托管代码的 Microsoft 单元测试框架和 Visual Studio 测试资源管理器创建、运行和自定义单元测试系列。

![icon-default.png?t=N7T8](https://i-blog.csdnimg.cn/blog_migrate/003a2ce7eb50c2e24a8c624c260c5930.png)
https://learn.microsoft.com/zh-cn/visualstudio/test/walkthrough-creating-and-running-unit-tests-for-managed-code?view=vs-2022](https://learn.microsoft.com/zh-cn/visualstudio/test/walkthrough-creating-and-running-unit-tests-for-managed-code?view=vs-2022 "C# 单元测试教程 - Visual Studio (Windows) | Microsoft Learn")

```cs
using test_UnitTest;

namespace UnitTest
{
    [TestClass]
    public class BankAccountTest
    {
        [TestMethod]
        //验证借出指定的金额后是否与预期的金额相等
        public void Debit_WithValidAmount_UpdatesBalance()
        {

            double beginningBalance = 11.99;    //初始金额
            double debitAmount = 4.55;          //借出去的金额数量
            double expected = 7.44;             //进出金额后期望剩余的金额数量
            BankAccount account = new BankAccount("张三", beginningBalance);

            account.Debit(debitAmount);

            double actual = account.Balance;
            //判断是否相等[若不相等则抛出异常]（运行测试后发现抛出了【该账户的金额并没有正确的借出去！！！】的异常；我们此时需要排查【account.Debit()】方法，
            //需要将【account.Debit()】方法的 m_balance += amout;修改为 m_balance -= amout;后重新运行即可通过单元测试）
            Assert.AreEqual(expected, actual, 0.001, "该账户的金额并没有正确的借出去！！！");
        }

        [TestMethod]
        //验证借出去的金额小于零时的行为是否正确（即：应该报错）
        public void Debit_WhenAmountIsLessThanZero_ShouldThrowArgumentOutOfRange()
        {
            double beginningBalance = 11.99;
            double debitAmount = -100;

            BankAccount bankAccount = new BankAccount("张三",beginningBalance);
            //使用 ThrowsException 方法断言已引发正确的异常。 除非 ArgumentOutOfRangeException 已引发，否则该方法将导致测试失败。
            //如果在借方金额小于零时，临时修改测试方法以引发更通用的 ApplicationException，则测试将正确运行，即测试将失败。
            Assert.ThrowsException<System.ArgumentOutOfRangeException>(() => bankAccount.Debit(debitAmount));


        }

        [TestMethod]
        //验证借出去的金额大于余额时的行为是否正确（即：应该报错）
        public void Debit_WhenAmountIsMoreThanBalance_ShouldThrowArgumentOutOfRange()
        {
            double beginningBalance = 11.99;
            double debitAmount =20.0;

            BankAccount bankAccount = new BankAccount("张三", beginningBalance);
            //使用 ThrowsException 方法断言已引发正确的异常。 除非 ArgumentOutOfRangeException 已引发，否则该方法将导致测试失败。
            //如果在借方金额大于余额时，临时修改测试方法以引发更通用的 ApplicationException，则测试将正确运行，即测试将失败。
            Assert.ThrowsException<System.ArgumentOutOfRangeException>(() => bankAccount.Debit(debitAmount));
        }

        [TestMethod]
        //该测试方法解决【没有办法知道哪个条件（amount > m_balance 或 amount < 0）导致在测试期间引发异常。
        //我们只知道在方法中引发了一个 ArgumentOutOfRangeException。
        //更理想的情况是，如果我们知道是 BankAccount.Debit 中的哪个条件导致引发异常（amount > m_balance 或 amount < 0），
        //这样就可以确信我们的方法可以正确合理地检查其自变量。】
        public void Debit_WhenAmountIsMoreThanBalance_ShouldThrowArgumentOutOfRange2()
        {
            // Arrange
            double beginningBalance = 11.99;
            double debitAmount = 20.0;
            BankAccount account = new BankAccount("张三", beginningBalance);

            // Act
            try
            {
                account.Debit2(debitAmount);
            }
            catch (System.ArgumentOutOfRangeException e)
            {
                // Assert
                StringAssert.Contains(e.Message, BankAccount.DebitAmountExceedsBalanceMessage);
            }
        }

        [TestMethod]
        //该测试方法解决【测试方法不会处理它原本应该处理的所有情况。
        //如果所测试的方法 Debit 在 debitAmount 大于余额（或小于零）时未能引发 ArgumentOutOfRangeException，则该测试方法通过。
        //这样并不好，因为如果未引发异常，则希望测试方法失败。这是测试方法中的一个 bug。
        //要解决该问题，在测试方法末尾添加 Assert.Fail 断言，处理未引发异常的情况。】
        public void Debit_WhenAmountIsMoreThanBalance_ShouldThrowArgumentOutOfRange3()
        {
            // Arrange
            double beginningBalance = 11.99;
            double debitAmount = 20.0;
            BankAccount account = new BankAccount("张三", beginningBalance);

            // Act
            try
            {
                account.Debit2(debitAmount);
            }
            catch (System.ArgumentOutOfRangeException e)
            {
                // Assert
                StringAssert.Contains(e.Message, BankAccount.DebitAmountExceedsBalanceMessage);
                return;
            }

            Assert.Fail("未引发预期的异常");
        }


    }//Class_end
}
```

## 三、单元测试资料

[Visual Studio 中的测试工具 - Visual Studio (Windows) | Microsoft Learn

了解如何使用功能 Visual Studio 来测试代码。

![icon-default.png?t=N7T8](https://i-blog.csdnimg.cn/blog_migrate/003a2ce7eb50c2e24a8c624c260c5930.png)
https://learn.microsoft.com/zh-cn/visualstudio/test/?view=vs-2022](https://learn.microsoft.com/zh-cn/visualstudio/test/?view=vs-2022 "Visual Studio 中的测试工具 - Visual Studio (Windows) | Microsoft Learn")

[单元测试入门 - Visual Studio (Windows) | Microsoft Learn

使用 Visual Studio 定义和运行单元测试，使代码保持正常运行并在客户之前找到错误和缺陷。

![icon-default.png?t=N7T8](https://i-blog.csdnimg.cn/blog_migrate/003a2ce7eb50c2e24a8c624c260c5930.png)
https://learn.microsoft.com/zh-cn/visualstudio/test/getting-started-with-unit-testing?view=vs-2022&tabs=dotnet%2Cmstest](https://learn.microsoft.com/zh-cn/visualstudio/test/getting-started-with-unit-testing?view=vs-2022&tabs=dotnet%2Cmstest "单元测试入门 - Visual Studio (Windows) | Microsoft Learn")
[单元测试基础知识 - Visual Studio (Windows) | Microsoft Learn

了解 Visual Studio 测试资源管理器如何提供灵活而高效的方法来运行单元测试并查看其结果。

![icon-default.png?t=N7T8](https://i-blog.csdnimg.cn/blog_migrate/003a2ce7eb50c2e24a8c624c260c5930.png)
https://learn.microsoft.com/zh-cn/visualstudio/test/unit-test-basics?view=vs-2022#write-your-tests](https://learn.microsoft.com/zh-cn/visualstudio/test/unit-test-basics?view=vs-2022#write-your-tests "单元测试基础知识 - Visual Studio (Windows) | Microsoft Learn")
[C# 单元测试教程 - Visual Studio (Windows) | Microsoft Learn

了解如何使用托管代码的 Microsoft 单元测试框架和 Visual Studio 测试资源管理器创建、运行和自定义单元测试系列。

![icon-default.png?t=N7T8](https://i-blog.csdnimg.cn/blog_migrate/003a2ce7eb50c2e24a8c624c260c5930.png)
https://learn.microsoft.com/zh-cn/visualstudio/test/walkthrough-creating-and-running-unit-tests-for-managed-code?view=vs-2022](https://learn.microsoft.com/zh-cn/visualstudio/test/walkthrough-creating-and-running-unit-tests-for-managed-code?view=vs-2022 "C# 单元测试教程 - Visual Studio (Windows) | Microsoft Learn")

[Assert Class (Microsoft.VisualStudio.TestTools.UnitTesting) | Microsoft Learn

A collection of helper classes to test various conditions within unit tests. If the condition being tested is not met, an exception is thrown.

![icon-default.png?t=N7T8](https://i-blog.csdnimg.cn/blog_migrate/003a2ce7eb50c2e24a8c624c260c5930.png)
https://learn.microsoft.com/zh-cn/dotnet/api/microsoft.visualstudio.testtools.unittesting.assert?view=visualstudiosdk-2022](https://learn.microsoft.com/zh-cn/dotnet/api/microsoft.visualstudio.testtools.unittesting.assert?view=visualstudiosdk-2022 "Assert Class (Microsoft.VisualStudio.TestTools.UnitTesting) | Microsoft Learn")