---
layout: post
title: "Linux下安装python3.6并建立软连接"
date: 2024-12-02 02:24:45 +0800
description: "乌班图的python2.7和python3.4安装位置/usr/local/lib安装python3"
keywords: "Ubuntu,Python3.6,编译安装"
categories: ['Python', 'Linux']
tags: ['无标签']
artid: "100146191"
image:
    path: https://api.vvhan.com/api/bing?rand=sj&artid=100146191
    alt: "Linux下安装python3.6并建立软连接"
render_with_liquid: false
featuredImage: https://bing.ee123.net/img/rand?artid=100146191
featuredImagePreview: https://bing.ee123.net/img/rand?artid=100146191
---

<div class="blog-content-box">
 <div class="article-header-box">
  <div class="article-header">
   <div class="article-title-box">
    <h1 class="title-article" id="articleContentId">
     Linux下安装python3.6并建立软连接
    </h1>
   </div>
  </div>
 </div>
 <article class="baidu_pl">
  <div class="article_content clearfix" id="article_content">
   <link href="../../assets/css/kdoc_html_views-1a98987dfd.css" rel="stylesheet"/>
   <link href="../../assets/css/ck_htmledit_views-704d5b9767.css" rel="stylesheet"/>
   <div class="htmledit_views" id="content_views">
    <p>
     乌班图的python2.7和python3.4安装位置
    </p>
    <p>
     /usr/local/lib
    </p>
    <p>
    </p>
    <p>
     <strong>
      安装python3.6
     </strong>
    </p>
    <p>
     <strong>
      下载python3.6.4
     </strong>
    </p>
    <p>
     wget https://www.python.org/ftp/python/3.6.4/Python-3.6.4.tgz
    </p>
    <p>
     <strong>
      解压
     </strong>
    </p>
    <p>
     tar -zxvf Python-3.6.4.tgz
    </p>
    <p>
    </p>
    <p>
     <strong>
      创建目录
     </strong>
    </p>
    <p>
     sudo mkdir /usr/local/python3.6
    </p>
    <p>
    </p>
    <p>
     <strong>
      编译安装（在解压出来的目录下执行）
     </strong>
    </p>
    <p>
     <strong>
      建议make和make install 分两步
     </strong>
    </p>
    <p>
     sudo ./configure --prefix=/usr/local/python3.6
    </p>
    <p>
     sudo make
    </p>
    <p>
     sudo make install
    </p>
    <p>
    </p>
    <p>
    </p>
    <p>
     <strong>
      删除软链接
     </strong>
    </p>
    <p>
     rm -rf /usr/bin/python3
    </p>
    <p>
     rm -rf /usr/bin/pip3
    </p>
    <p>
    </p>
    <p>
    </p>
    <p>
     <strong>
      建立新的指向python3.6的软链接
     </strong>
    </p>
    <p>
     sudo ln -s /usr/local/python3.6/bin/python3.6 /usr/bin/python3
    </p>
    <p>
     sudo ln -s /usr/local/python3.6/bin/pip3.6 /usr/bin/pip3
    </p>
    <p>
    </p>
    <p>
    </p>
    <p>
     python3 查看
    </p>
    <p>
    </p>
    <p>
     <strong>
      pip3 install 安装软件报错
     </strong>
    </p>
    <p>
     报错：
    </p>
    <p>
     /usr/local/python3.6/lib/python3.6/site-packages/pip/_vendor/distro.py
    </p>
    <p>
     raise subprocess.CalledProcessError(code, cmd, stdout, stderr) subprocess.CalledProcessError: Co
    </p>
    <p>
    </p>
    <p>
     **kwargs).stdout File "/home/lab/anaconda3/envs/python3/lib/python3.7/subprocess.py", line 487, in run output=stdout, stderr=stderr) subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1.
    </p>
    <p>
    </p>
    <p>
     这里的问题主要出在 lsb_release 包上, 此处可通过修改conda中pip下的 distro.py , 编辑其初始化方法的 include_lsb属性为False.
    </p>
    <p>
    </p>
    <p>
     stackoverflow - 解答:
    </p>
    <p>
     I had the same problem on a shared hosting account
    </p>
    <p>
     which is very limiting (I was installing python and pip for my user only).
    </p>
    <p>
     Their lsb_release -a returns something non-standard
    </p>
    <p>
     and I cannot change it.
    </p>
    <p>
     I solved the issue by editing distro.py
    </p>
    <p>
     (in your case: /usr/local/lib/python3.6/dist-packages/pip/_vendor/distro.py)
    </p>
    <p>
     and changing the default parameter of __init__ method.
    </p>
    <p>
     In my version it was at the line 545. Snippet: def __init__(self, include_lsb=True, os_release_file='', distro_release_file=''): Just change include_lsb=True to include_lsb=False.
    </p>
    <p>
    </p>
    <p>
     即:
    </p>
    <p>
     def __init__(self,
    </p>
    <p>
     include_lsb=False,    # 这里把True改成False
    </p>
    <p>
     os_release_file='',
    </p>
    <p>
     distro_release_file='',
    </p>
    <p>
     include_uname=True):
    </p>
    <p>
    </p>
    <p>
     <strong>
      编辑这个报错的文件
     </strong>
    </p>
    <p>
     <strong>
      sudo vim /usr/local/python3.6/lib/python3.6/site-packages/pip/_vendor/distro.py
     </strong>
    </p>
    <p>
    </p>
    <p>
     <strong>
      把include_lsb的True改成False
     </strong>
    </p>
    <p>
     <strong>
      include_lsb=False
     </strong>
    </p>
    <p>
    </p>
    <p>
    </p>
    <p>
    </p>
    <p>
     <strong>
      第二个报错
     </strong>
    </p>
    <p>
     The directory '/home/rongyi/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    </p>
    <p>
     The directory '/home/rongyi/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    </p>
    <p>
    </p>
    <p>
     <strong>
      解决方法如下：
     </strong>
    </p>
    <p>
     sudo chown -R root /home/rongyi/.cache/pip/
    </p>
    <p>
     sudo chown -R root /home/rongyi/.cache/pip/http/
    </p>
    <p>
    </p>
   </div>
  </div>
 </article>
 <p alt="68747470733a2f2f:626c6f672e6373646e2e6e65742f657a7265616c5f74616f2f:61727469636c652f64657461696c732f313030313436313931" class_="artid" style="display:none">
 </p>
</div>


